In [21]:
import pymysql as pydb
pydb.install_as_MySQLdb()
import MySQLdb
from sqlalchemy import create_engine

In [22]:
user = 'ryuiks'
password = '1q2w3e4r!!'
db_name = 'db_aiam_analysis'

engine = create_engine("mysql+mysqldb://"+user+":"+password+"@10.17.126.105/"+db_name, encoding='utf-8')
conn = engine.connect()

In [23]:
import pandas as pd

sql = "select * from usetf_basic_data where country='U.S.' "
df = pd.read_sql_query(sql=sql, con=engine)
df.tail()

# conn.close()

,ticker,name,intro,issuer,brand,structure,expense_ratio,inception,tax_form,index_ticker,...,asset_class_size,asset_class_style,region,country,sector_general,sector_specific,duration,currency,aum,shares
591,SDYL,ETRACS Monthly Pay 2xLeveraged S&P Dividend ETN,None,UBS Global Asset Management,0,ETN,0.0030,2012-05-22,1099,SPHYDA,...,Multi-Cap,Blend,North America,U.S.,None,None,None,None,9.982151,0.1165
592,BDCS,UBS E-TRACS Wells Fargo Business Development C...,None,UBS Global Asset Management,0,ETN,0.0085,2011-04-27,1099,WFBDCPX,...,Micro-Cap,Blend,North America,U.S.,Financials,Business Development Company,None,None,26.883860,1.7654
593,MLPG,UBS E-TRACS Alerian Natural Gas MLP Index Fund,None,UBS Global Asset Management,0,ETN,0.0085,2010-07-13,1099,ANGI,...,Multi-Cap,Blend,North America,U.S.,Energy,MLP,None,None,2.562389,0.2142
594,MLPI,UBS E-TRACS Alerian MLP Infrastructure ETN,None,UBS Global Asset Management,0,ETN,0.0085,2010-03-31,1099,AMZI,...,Multi-Cap,Blend,North America,U.S.,Energy,MLP,None,None,46.375510,4.1155
595,QVM,Arrow QVM Equity Factor ETF,None,ArrowShares,0,ETF,0.0065,2015-02-27,1099,AIQVM,...,Mega-Cap,Blend,North America,U.S.,None,None,None,None,5.133363,0.2500

In [24]:
df.head(3)

,ticker,name,intro,issuer,brand,structure,expense_ratio,inception,tax_form,index_ticker,...,asset_class_size,asset_class_style,region,country,sector_general,sector_specific,duration,currency,aum,shares
0,UVXY,ProShares Ultra VIX Short-Term Futures,This ETF offers leveraged exposure to an index...,ProShares,ProShares,ETF,0.009500,2011-10-04,K-1,SPVXSP,...,None,None,North America,U.S.,None,None,None,None,891.39250,213.780912
1,SPY,SPDR S&P 500 ETF,SPY is one of the largest and most heavily-tra...,State Street,SPDR,ETF,0.000945,1993-01-22,1099,SPXT,...,Large-Cap,Blend,North America,U.S.,None,None,None,None,358125.34380,872.632116
2,XLF,Financial Select Sector SPDR Fund,"This ETF, one of the powerhouse SPDR products,...",State Street,SPDR,ETF,0.001200,1998-12-22,1099,IXMTR,...,Large-Cap,Blend,North America,U.S.,Financials,Broad,None,None,44914.07422,1185.395427

In [30]:
sql = f"""select a.str_code, a.activate, cal_profit(a.str_code, '2021-07-29', 0) 1d, cal_profit(a.str_code, '2021-07-29', 7) 1w										
,cal_profit(a.str_code, '2021-07-29', 14) 2w, cal_profit(a.str_code, '2021-07-29', 30) 1m										
,cal_profit(a.str_code, '2021-07-29', 91) 3m, cal_profit(a.str_code, '2021-07-29', 182) 6m										
,cal_profit(a.str_code, '2021-07-29', 365) 1y, cal_profit(a.str_code, '2021-07-29', 1000) cum										
,cal_hit(a.str_code, '2021-07-29', 1000) hit, cal_vol(a.str_code, '2021-07-29', 365) vol										
from dm_strategys a, select_return b  where b.date = '2021-07-29' and a.str_code = b.str_code and a.activate > 0;
"""

print(sql)
df = pd.read_sql_query(sql=sql, con=engine)

select a.str_code, a.activate, cal_profit(a.str_code, '2021-07-29', 0) 1d, cal_profit(a.str_code, '2021-07-29', 7) 1w
,cal_profit(a.str_code, '2021-07-29', 14) 2w, cal_profit(a.str_code, '2021-07-29', 30) 1m
,cal_profit(a.str_code, '2021-07-29', 91) 3m, cal_profit(a.str_code, '2021-07-29', 182) 6m
,cal_profit(a.str_code, '2021-07-29', 365) 1y, cal_profit(a.str_code, '2021-07-29', 1000) cum
,cal_hit(a.str_code, '2021-07-29', 1000) hit, cal_vol(a.str_code, '2021-07-29', 365) vol
from dm_strategys a, select_return b  where b.date = '2021-07-29' and a.str_code = b.str_code and a.activate > 0;

In [31]:
print(df.shape)
df.head(3)

(12, 12)

,str_code,activate,1d,1w,2w,1m,3m,6m,1y,cum,hit,vol
0,dm_165_0,2,0.0,0.09,-0.12,-0.24,-0.24,-0.24,-0.24,-0.24,0.461538,1.27
1,dm_165_1,2,0.0,0.02,-0.11,0.40,0.40,0.40,0.40,0.40,0.538462,1.90
2,dm_165_2,2,0.0,0.02,-0.09,0.40,0.40,0.40,0.40,0.40,0.538462,1.81

In [28]:
# df.to_dict()
# print(df.to_html())